server:
  port: 9095
  servlet:
    application-display-name: "ccccs"
    context-path: "/fl/"
spring:
  # 国际化（消息源自动配置,springboot默认找出messages）
  messages:
    basename: i18n.messages
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.7:3306/fl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.7:3306/fl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: 123456
      #连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒
      initial-size: 10
      max-active: 60
      min-idle: 10
      max-wait: 60000
      #不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #作用：1) Destroy线程会检测连接的间隔时间                2) testWhileIdle的判断依据
      time-between-eviction-runs-millis: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  redis:
    host: 127.0.0.1
mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  configuration:
    cache-enabled: true
    local-cache-scope: session
logging:
  level:
    com.example.service.SystemUserMapper: debug
custom:
  zfl:
    username: fl
    password: 123456
